In [15]:
import numpy as np

np.array([[(x+y)%2 for x in range(8)] for y in range(8)])

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [16]:
np.array(np.arange(0, 25)%5).reshape(5, 5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [17]:
np.random.random((3, 3, 3))

array([[[0.33579979, 0.76628216, 0.67909555],
        [0.07458708, 0.4620777 , 0.86892937],
        [0.66525738, 0.21159742, 0.36329   ]],

       [[0.61783201, 0.30878386, 0.87016641],
        [0.4100946 , 0.5014623 , 0.17104835],
        [0.53101871, 0.27236724, 0.19836371]],

       [[0.51213691, 0.80223667, 0.66710012],
        [0.109707  , 0.52581573, 0.23723768],
        [0.50269045, 0.05706576, 0.35272233]]])

In [18]:
np.matrix([[1, 1, 1], [1, 0, 1], [1, 1, 1]])

matrix([[1, 1, 1],
        [1, 0, 1],
        [1, 1, 1]])

In [24]:
np.sort(np.random.random(20))[::-1]

array([0.93675212, 0.93161601, 0.80354807, 0.70005452, 0.67712837,
       0.52935742, 0.52105239, 0.51708687, 0.44030155, 0.43807446,
       0.32264511, 0.31041651, 0.18116043, 0.15204532, 0.11913367,
       0.11671837, 0.09018756, 0.03894435, 0.0343114 , 0.00349467])

In [30]:
m = np.asmatrix(np.random.random(20).reshape(4, 5))
print(m, m.shape , m.size, sep='\n')

[[0.83701045 0.53127564 0.39738705 0.61783054 0.0149041 ]
 [0.30754533 0.95282589 0.10713849 0.05150331 0.23393991]
 [0.33318422 0.81970209 0.23610692 0.17638381 0.83388775]
 [0.42652614 0.75568372 0.20770955 0.36876588 0.682221  ]]
(4, 5)
20


In [65]:
import pandas as pd

a = pd.Series([0, 0])
b = pd.Series([1, 1])
print(sum((a-b)**2)**0.5)

1.4142135623730951


In [67]:
apple_data = pd.read_csv('/Users/aleksandrlazarev/Documents/AAPL.csv')
apple_data

Date        Open        High         Low       Close   Adj Close  \
0    2021-01-04  133.520004  133.610001  126.760002  129.410004  127.331680   
1    2021-01-05  128.889999  131.740005  128.429993  131.009995  128.905960   
2    2021-01-06  127.720001  131.050003  126.379997  126.599998  124.566818   
3    2021-01-07  128.360001  131.630005  127.860001  130.919998  128.817429   
4    2021-01-08  132.429993  132.630005  130.229996  132.050003  129.929306   
..          ...         ...         ...         ...         ...         ...   
247  2021-12-27  177.089996  180.419998  177.070007  180.330002  178.527771   
248  2021-12-28  180.160004  181.330002  178.529999  179.289993  177.498154   
249  2021-12-29  179.330002  180.630005  178.139999  179.380005  177.587265   
250  2021-12-30  179.470001  180.570007  178.089996  178.199997  176.419052   
251  2021-12-31  178.089996  179.229996  177.259995  177.570007  175.795334   

        Volume  
0    143301900  
1     97664900  
2    155088000  
3    109578200  
4    105158200  
..         ...  
247   74919600  
248   79144300  
249   62348900  
250   59773000  
251   64062300  

[252 rows x 7 columns]

In [135]:
a = [1, 3, 2, 6, 5, 4, 27]
ans = 1^2^3^4^5^6^7
for i in range(1, len(a)):
    ans = ans ^ a[i]
print(ans)

29
